In [1]:
import numpy as np

In [2]:
arr = np.array([3,6,32,7])

In [3]:
arr

array([ 3,  6, 32,  7])

In [4]:
arr[0]

np.int64(3)

In [5]:
arr1 = np.array([[3,6,32,7]])

In [6]:
arr1

array([[ 3,  6, 32,  7]])

In [7]:
arr1[0,1]

np.int64(6)

In [8]:
arr.shape

(4,)

In [9]:
arr.dtype

dtype('int64')

In [10]:
arr1[0,1]=45

In [11]:
arr1

array([[ 3, 45, 32,  7]])

# Array Creation : Conversion from other  Python Structure

In [12]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [13]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [14]:
listarray.dtype

dtype('int64')

In [15]:
listarray.shape

(3, 3)

In [16]:
listarray.size

9

In [17]:
zeros=np.zeros([2,5])

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
zeros.size

10

In [22]:
range = np.arange(15)

In [23]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
lspace = np.linspace(1,5,12)

In [25]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
lspace1 = np.linspace(1,50,10)

In [27]:
lspace1

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [28]:
emp = np.empty((4,6))

In [29]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56602523e-307, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037657e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [1.42421160e-306, 6.23055651e-307, 7.56595733e-307,
        1.37961302e-306, 8.34451503e-308, 2.22507386e-306]])

In [30]:
emp_like = np.empty_like(lspace)

In [31]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [32]:
id = np.identity(5)

In [33]:
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
id.shape

(5, 5)

In [35]:
arr2 = np.arange(99)

In [36]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [37]:
arr2.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr2 = arr2.reshape(3,33)

In [40]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [43]:
arr3 = np.array(x)

In [44]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
arr3.sum(axis=0)

array([12,  8,  9])

In [46]:
arr3.sum(axis=1)

array([ 6, 15,  8])

In [47]:
arr3.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
arr3.flat

In [49]:
for item in arr3.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [50]:
arr3.ndim

2

In [51]:
arr3.size

9

In [52]:
arr3.nbytes

72

In [53]:
arr4 = np.array([1,3,4,634,2])

In [54]:
arr4

array([  1,   3,   4, 634,   2])

In [55]:
arr4.argmax()

np.int64(3)

In [56]:
arr4.argmin()

np.int64(0)

In [57]:
arr4.argsort()

array([0, 4, 1, 2, 3])

In [58]:
arr3.argmin()

np.int64(8)

In [59]:
arr3.argmax()

np.int64(6)

In [60]:
arr3.argmax(axis=0)

array([2, 1, 1])

In [61]:
arr3.argmax(axis=1)

array([2, 2, 0])

In [62]:
arr3.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [63]:
arr3.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [64]:
arr3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [65]:
arr5 = np.array([[1,2,1],[4,0,6],[8,1,0]])

In [66]:
arr5

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [67]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
arr3+arr5

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [69]:
arr3*arr5

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [70]:
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [71]:
np.where(arr3>5)

(array([1, 2]), array([2, 0]))

In [72]:
np.count_nonzero(arr3)

8

In [73]:
np.nonzero(arr3)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [74]:
import sys

In [75]:
py_ch = [0,4,55,2]

In [76]:
np_ch = np.array(py_ch)

In [77]:
py_ch

[0, 4, 55, 2]

In [78]:
np_ch

array([ 0,  4, 55,  2])

In [79]:
sys.getsizeof(1)*len(py_ch)

112

In [80]:
np_ch.itemsize*np_ch.size

32

In [81]:
arr6 = np.array([10,20,30,40])

In [82]:
arr6

array([10, 20, 30, 40])

In [83]:
arr6.dtype

dtype('int64')

In [84]:
print(type(arr6))

<class 'numpy.ndarray'>


In [85]:
print(arr6[0:3])

[10 20 30]


In [86]:
print(arr6[1:3])

[20 30]


In [87]:
print(arr6[1:])

[20 30 40]


In [88]:
arr7 = np.array([[10,20,30,40],[50,60,70,80]])
arr7

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [89]:
print(arr7[0:2,0:2])

[[10 20]
 [50 60]]


In [90]:
print(arr7[0:2,0:3])

[[10 20 30]
 [50 60 70]]


In [91]:
print(arr7[0,0:3])

[10 20 30]


In [92]:
print(arr7[1,1:3])

[60 70]


In [93]:
arr7.shape

(2, 4)

In [94]:
arr7.size

8

In [95]:
len(arr7)

2

In [96]:
print(arr7.shape)
print(arr7.size)
print(len(arr7))
print(type(arr7))
print(arr7.dtype)
print(arr7.astype(float))

(2, 4)
8
2
<class 'numpy.ndarray'>
int64
[[10. 20. 30. 40.]
 [50. 60. 70. 80.]]


# Mathematical Operations

In [97]:
a = np.array([30,40,60,20,10])
b = np.array([30,20,10,20,20])
print(a+b)
print(np.add(a,b))

[60 60 70 40 30]
[60 60 70 40 30]


In [98]:
c = np.array([[30,40],[20,10]])
d = np.array([[30,20],[10,20]])
print(np.add(c,d))

[[60 60]
 [30 30]]


In [99]:
print(c-d)
print(np.subtract(c,d))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [100]:
print(c*d)
print(np.multiply(c,d))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [101]:
print(c/d)
print(np.divide(c,d))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [102]:
e = np.array([3,4,2,1])
f = np.array([2])
print(np.power(e,f))

[ 9 16  4  1]


In [103]:
g = np.array([25,100,169,81])
print(np.sqrt(g))

[ 5. 10. 13.  9.]


# Combining and Splitting Arrays

In [104]:
a=[30,40,50]
b=b=[5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


# Concatenate

In [106]:
ar1 = np.array([30,40,50])
ar2 = np.array([5,5,3])
print(np.concatenate([ar1,ar2]))

[30 40 50  5  5  3]


In [107]:
print(np.concatenate([ar1,ar2],axis=0))

[30 40 50  5  5  3]


In [111]:
ar3 = np.array([[30,40],[50,10]])
ar4 = np.array([[5,5],[3,3]])
print(np.concatenate([ar3,ar4]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [112]:
print(np.concatenate([ar3,ar4],axis=1))

[[30 40  5  5]
 [50 10  3  3]]


In [113]:
print(np.concatenate([ar3,ar4],axis=0))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [115]:
print(np.hstack([ar3,ar4]))  #Horizontal Concatenation

[[30 40  5  5]
 [50 10  3  3]]


In [116]:
print(np.vstack([ar3,ar4]))  #Vertical Concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [120]:
#Splitting
ar5 = np.array([20,40,30,40,10,20])
print(np.array_split(ar5,3))
print(np.array_split(ar5,3)[1])
print(np.array_split(ar5,4))
print(np.array_split(ar5,5))

[array([20, 40]), array([30, 40]), array([10, 20])]
[30 40]
[array([20, 40]), array([30, 40]), array([10]), array([20])]
[array([20, 40]), array([30]), array([40]), array([10]), array([20])]


In [124]:
ar6 = np.array([[20,40,30],[40,10,20]])
print(np.array_split(ar6,2))
print(np.array_split(ar6,3))
print(np.array_split(ar6,4))

[array([[20, 40, 30]]), array([[40, 10, 20]])]
[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int64)]
[array([[20, 40, 30]]), array([[40, 10, 20]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]


**Adding and Removing Elements in the Arrays**

In [126]:
#Append
ar7 = np.array([20,40,60,80])
print(np.append(ar7,90))

[20 40 60 80 90]


In [127]:
ar8 = np.array([[20,40],[60,80]])
print(np.append(ar8,90))

[20 40 60 80 90]


In [128]:
#Insert
print(np.insert(ar7,1,50))

[20 50 40 60 80]


In [129]:
print(np.insert(ar8,1,50))

[20 50 40 60 80]


In [130]:
print(np.insert(ar8,1,[50,60]))

[20 50 60 40 60 80]


In [133]:
print(np.insert(ar8,1,[50,60],axis=1))

[[20 50 40]
 [60 60 80]]


In [135]:
print(np.insert(ar8,1,[50,60],axis=0))

[[20 40]
 [50 60]
 [60 80]]


In [136]:
print(np.insert(ar8,1,[50],axis=1))

[[20 50 40]
 [60 50 80]]


In [137]:
print(np.insert(ar8,[1,2],[50],axis=1))

[[20 50 40 50]
 [60 50 80 50]]


In [138]:
print(np.insert(ar8,[1,2],[50],axis=0))

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [139]:
#Delete
print(np.delete(ar8,1))

[20 60 80]


In [140]:
print(np.delete(ar8,1,axis=0))

[[20 40]]


In [141]:
print(np.delete(ar8,1,axis=1))

[[20]
 [60]]


**Search, sort and Filter**

In [143]:
#Sort
ar9 = np.array([7,8,4,12,9])
print(np.sort(ar9))

[ 4  7  8  9 12]


In [145]:
ar10 = np.array([[7,8,4,12,9],[2,8,5,1,3]])
print(np.sort(ar10))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [146]:
#Search
s = np.where(ar9 == 4)
print(s)

(array([2]),)


In [147]:
p = np.where(ar9%2 == 0)
print(p)

(array([1, 2, 3]),)


In [156]:
#Search Sorted(Arry should be sorted)
a = np.array([1,2,3,4,5])
q = np.searchsorted(a,2)
r = np.searchsorted(a,5)
print(q)
print(r)

1


In [157]:
#Filter
ar11 = np.array([20,30,40,50])
fa = [True, False, True, False]  # Values should be same (Number of Values)
new = ar11[fa]
print(new)

[20 40]


In [158]:
fa1 = [False, False, True, False]
new1 = ar11[fa1]
print(new1)


[40]


In [159]:
fa2 = ar11>35
new2 = ar11[fa2]
print(new2)

[40 50]


**Aggregating Functions in Numpy**

In [160]:
print(ar7)

[20 40 60 80]


In [162]:
print(np.sum(ar7))
print(np.min(ar7))
print(np.max(ar7))
print(np.size(ar7))
print(np.mean(ar7))
print(np.cumsum(ar7))   #Cumulative sum
print(np.cumprod(ar7))  #Cumulative Product

200
20
80
4
50.0
[ 20  60 120 200]
[     20     800   48000 3840000]


In [174]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
print(price,"\n",quantity)
c = np.cumprod([price,quantity],axis=0)
print(c)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
31270


**Statistical Functions in Arrays**

In [179]:
baked_food = [200,300,150,130,200,280,170,188]
import statistics as sts
d = np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(sts.mode(baked_food))
print(np.std(baked_food))  #Standard Deviation
print(np.var(baked_food))  #Variance=(std)^2

202.25
194.0
200
55.68157235567257
3100.4375


In [180]:
#Coefficiant of correlation
#-1 represent inversely proportional relationship
#1 represent proportional relationship
#0 means no relationship or Neutral

tobacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]
print(np.corrcoef([tobacco_consumption,deaths]))  #Coefficiant of Correlation

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [182]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]
print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
